apiVersion: 1

# Grafana datasource configuration for Prometheus

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: POST
    secureJsonData:
      httpHeaderValue1: "${PROMETHEUS_AUTH_TOKEN}"
    json:
      tlsSkipVerify: true
      managedAlerts: true
    uid: prometheus-workshopsai-cms

  - name: CloudWatch
    type: cloudwatch
    access: proxy
    editable: true
    jsonData:
      authType: default
      defaultRegion: us-east-1
      assumeRoleArn: ${GRAFANA_ASSUME_ROLE_ARN}
    secureJsonData:
      accessKeyId: ${GRAFANA_AWS_ACCESS_KEY}
      secretAccessKey: ${GRAFANA_AWS_SECRET_KEY}
    uid: cloudwatch-workshopsai-cms

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
    uid: loki-workshopsai-cms

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "logstash-*"
    jsonData:
      interval: "Daily"
      timeField: "@timestamp"
      esVersion: 8.0.0
      maxConcurrentShardRequests: 5
      logMessageField: "message"
      logLevelField: "level"
    secureJsonData:
      basicAuthPassword: ${ELASTICSEARCH_PASSWORD}
      basicAuthUser: ${ELASTICSEARCH_USERNAME}
    uid: elasticsearch-workshopsai-cms